# Generated by Django 3.0.6 on 2020-06-03 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='award_name',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='category_name',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='country_name',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=300)),
                ('budget', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('avg_rank', models.FloatField(null=True)),
                ('summary', models.TextField(default='', max_length=5000)),
                ('revenue', models.IntegerField(null=True)),
                ('language', models.CharField(default='', max_length=300)),
                ('image', models.URLField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(default='', max_length=300)),
                ('person_lastname', models.CharField(default='', max_length=300)),
                ('person_birthdate', models.DateField()),
                ('person_deathdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('production_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='soundtrack',
            fields=[
                ('soundtrack_id', models.AutoField(primary_key=True, serialize=False)),
                ('soundtrack_name', models.CharField(default='', max_length=300)),
                ('writer_name', models.CharField(default='', max_length=300)),
                ('singer', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=5000)),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='release_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=300)),
                ('release_date', models.CharField(default='', max_length=300)),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='production_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('production_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.production')),
            ],
        ),
        migrations.CreateModel(
            name='movie_soundtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('sountrack_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.soundtrack')),
            ],
        ),
        migrations.CreateModel(
            name='movie_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.keywords')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='movie_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.genres')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='movie_crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(default='', max_length=300)),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.departments')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='movie_cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(default='', max_length=300)),
                ('character_order', models.IntegerField()),
                ('gender_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.country_name')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='character_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=300)),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('award_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.award_name')),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.category_name')),
                ('movie_id', models.ManyToManyField(to='main.Movie')),
            ],
        ),
    ]
