# Generated by Django 2.0 on 2020-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_birthdate',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_deathdate',
            field=models.CharField(default='', max_length=300),
        ),
    ]
