# Generated by Django 2.0 on 2020-06-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200604_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_crew',
            name='job',
        ),
        migrations.AddField(
            model_name='departments',
            name='job',
            field=models.CharField(default='', max_length=300),
        ),
    ]
